.change_rules_helm:
  before_script: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - &changes_helm
      changes:
        - .gitlab-ci.yml
        - charts/argo-cd/*


Helm lint:
  stage: test
  extends: .change_rules_helm
  image:
    name: alpine/helm:3.3.1
    entrypoint: [""]
  script:
    - cd charts/argo-cd
    - helm dep update
    - helm lint .
  needs: []

Helm push:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - .gitlab-ci.yml
      - charts/argo-cd/*
  image:
    name: alpine/helm:3.3.1
    entrypoint: [""]
  script:
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - cd charts/argo-cd
    - helm repo add helm_repo $HELM_REPO_URL --username $HELM_REPO_USER --password $HELM_REPO_PASS
    - helm dep update
    - helm cm-push . helm_repo
  needs:
    - Helm lint