apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argo-cd.controller.fullname" . }}-argocd-full-access
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-argocd-full-access
subjects:
- kind: ServiceAccount
  name: {{ include "argo-cd.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
