{{- $serviceName := include "argo-cd.server.fullname" . -}}
{{- $servicePort :=  .Values.server.service.servicePortHttp -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.customExternalDnsName }}
    kubernetes.io/ingress.class: {{ .Values.customIngressControllerClassAnnotation }}
    {{- end }}
    {{- if .Values.server.certificate.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    {{- end }}
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ template "argo-cd.server.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
spec:
  rules:
    - host: {{ include "coreweave.externalDnsName" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  {{- if kindIs "float64" $servicePort }}
                  number: {{ $servicePort }}
                  {{- else }}
                  name: {{ $servicePort }}
                  {{- end }}
  {{- if .Values.server.certificate.enabled }}
  tls:
    - hosts:
      - {{ include "coreweave.externalDnsName" . }}
      secretName: {{ include "coreweave.certSecretName" . }}
  {{- end }}
